config/routes.rb
Rails.application.routes.draw do

  root 'blogs#index'
  get 'blogs/like'
  resources :blogs do
    resources :replies
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :replies
  validates :body,presence: true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :blog
  validates :comment,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blog=Blog.new
    @blogs=Blog.all
  end

  def new
    @blog=Blog.new
  end

  def show
    @blog=Blog.find(params[:id])
  end

  def create
    @blog=Blog.new(blog_params)
    if @blog.save
      redirect_to root_url
    end
  end

  def like
    @blog=Blog.find(params[:blog_id])
    @blog.like+=1
    @blog.save
  end

  private
  def blog_params
    params.require(:blog).permit(:body,:like)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def index
    @replies=Reply.all
  end

  def new
    @reply=Reply.new
  end

  def create
    @blog=Blog.find(params[:blog_id])
    @reply=@blog.replies.create(reply_params)
    if @reply.save
      redirect_to @blog
    end
  end

  private
  def reply_params
    params.require(:reply).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/blogs/_form.html.erb
<%=form_for(@blog) do |f| %>
  <%=f.text_field :body,placeholder:"投稿しよう" %>
  <%=f.submit "投稿する"%>
<% end %>

app/views/blogs/index.html.erb
<h1>Mini blog</h1>

<%=render 'form' %>

<% @blogs.each do |blog| %>
  <h3>
    <%=blog.id %>:
    <%=link_to blog.body,blog%>
  </h3>
  <p>
    <%=link_to 'いいね:',blogs_like_path(blog_id: blog.id),remote:true %>
    <span id="like-count-<%=blog.id%>">
      <%=blog.like %> ｜
    </span>
    コメント数:<%=blog.replies.count %> ｜
    投稿日時:<%=blog.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
  </p>
<%end %>

app/views/blogs/like.js.erb
$('#like-count-<%=@blog.id%>').html("<%= @blog.like %> ｜");

app/views/blogs/show.html.erb
<h1>Mini blog</h1>
<%=link_to "戻る",blogs_path %>
<p>
  <%=@blog.id %>:
  投稿日時:<%=@blog.created_at %> ｜
  <%=link_to 'いいね:',blogs_like_path(blog_id: @blog.id),remote:true %>
  <span id="like-count-<%=@blog.id%>">
    <%=@blog.like %> ｜
  </span>
</p>

<h4>
  <%=@blog.body %>
</h4>

<%=form_for([@blog,@blog.replies.build]) do |f| %>
  <%=f.text_field :comment,placeholder:"コメントしよう" %>
  <%=f.submit "コメントする" %>
<% end %>

<% @blog.replies.each do |reply| %>
  <p>
    <%=reply.comment %>
    <%=reply.created_at.try(:strftime,'%Y/%m/%d %H:%M:%S')%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InternW2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>